### ISSUE TITLE
Make the night mode toggleable

### ISSUE THREAD

**Issue by ShadyMedic** [johncoxon/automatic-dark-mode#2]
I have the dark mode set on my Windows machine, but I prefer to have Anki in the light mode during the day. I want to have Anki in dark mode only at the night, so it's easier on my eyes. That's not the case with Windows.

Currently, I always have the dark mode in Anki (unless I disable the addon and restart the whole program, which is quite inconvenient).

Would it be possible to make the addon add an option to the "Settings" tab in the application header, which would turn the dark mode on or off upon clicking? If you wanted to improve this even further, you could add a time setting, which would turn the dark mode on automatically when a specified time of the day is reached (and turned off when another time is reached).

**Comment by johncoxon** [comment]
This is the sort of thing that might be handled better in a separate plugin, I'm afraid – I'd need to do things like store the preference and create UI elements, which are things that this plugin doesn't currently do, and I'm not sure I have time to implement those features.

Feel free to fork the repo, though! 😄
