### ISSUE TITLE
not switching automaticly on mac

### ISSUE THREAD

**Issue by fantomovics** [johncoxon/automatic-dark-mode#3]
On mac os i must to restart the app to switch the mode correctly. (but after restarting its works perfectly)
It would be truly automatic if I didn’t have to do that.
Its looks like this when the os switch to dark mode, if i dont restart the app:
<img width="996" alt="Screenshot 2022-05-23 at 10 49 00" src="https://user-images.githubusercontent.com/63469704/169781434-0477ebd0-e5d7-400b-acfa-a7181faf5003.png">

**Comment by johncoxon** [comment]
Hi fantomovics, this is an Anki bug. It's fixed in Anki 2.1.52 on my machine, which also introduces automatic dark mode switching without the plugin, so you can just update Anki and remove my plugin to solve the issue.
